POST http://localhost:8000/api/users/
Content-Type: application/json

{
    "name": "name",
    "surname": "surname",
    "email": "name@gmail.com",
    "phone": "456",
    "password": "pssw",
    "role": "admin",
    "country": "Turkiye",
    "city": "Izmir",
    "address": "Izmir",
    "birthdate": "2023/05/05"
}

###
GET http://localhost:8000/api/users

###
POST http://localhost:8000/api/auth/login

{
    "email": "ezgi@gmail.com",
    "password": "sdfddf"
}
